### ISSUE TITLE
change group -> groups in acl_lists, 

### ISSUE THREAD

**Issue by cinek810** [cinek810/ansible-deployer#101]
this should be a list to allow multiple OS groups in on acl entry

**Comment by cinek810** [comment]
Move infra to upper level?  Need to think about that/discuss

**Comment by cinek810** [comment]
maybe move stages to uppre level too..

**Comment by LegenJCdary** [comment]
Fine for me, we don't even have to touch infra/stage pair. Seems working, writing tests rn.

**Comment by LegenJCdary** [comment]
fixed in #109
