### ISSUE TITLE
Change allow_for to use "acl_list" instead of direct entries

### ISSUE THREAD

**Issue by cinek810** [cinek810/ansible-deployer#76]
acl_lists:
  - rootOnAll:
    - group: root
      infra:
       - name: testInfra
      stages:
      - testing
      - prod
      - locked

tasks:
 - name: task_exec_bin_true
 play_items:
 - run_bin_true
 allowed_for:
 - rootOnAll

**Comment by LegenJCdary** [comment]
done in #83
